# Generated by Django 5.2.5 on 2025-08-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rubrique_remove_video_category_contenu_delete_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubrique',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rubrique',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/'),
        ),
    ]
