# Generated by Django 5.2.5 on 2025-08-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_rubrique_description_alter_rubrique_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
